apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging-gateway
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: doug@linsmeyer.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        gatewayHTTPRoute:
          parentRefs:
          - name: scavenger-hunt-gateway
            namespace: scavenger-hunt-prod
            kind: Gateway
            group: gateway.networking.k8s.io