# Staging-specific patches for NGINX Fabric Gateway
---
# Update Gateway with staging domain
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: scavenger-hunt-gateway
spec:
  addresses:
  - type: Hostname
    value: staging.scavengerhunt.example.com
---
# Update HTTPRoutes with staging hostnames
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api-route
spec:
  hostnames:
  - staging.scavengerhunt.example.com
  - api-staging.scavengerhunt.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin-dashboard-route
spec:
  hostnames:
  - staging.scavengerhunt.example.com
  - admin-staging.scavengerhunt.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: player-app-route
spec:
  hostnames:
  - staging.scavengerhunt.example.com
  - play-staging.scavengerhunt.example.com
---
# Relaxed rate limits for staging/testing
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: api-ratelimit-policy
spec:
  rateLimit:
    requests: 200  # Increased for testing
    burst: 50
---
# Higher sampling rate for staging
apiVersion: gateway.nginx.org/v1alpha1
kind: ObservabilityPolicy
metadata:
  name: tracing-policy
spec:
  tracing:
    otel:
      samplingRate: 0.5  # 50% sampling in staging for better debugging