# Staging-specific patches for NGINX Fabric Gateway
---
# Update Gateway with staging domain
apiVersion: gateway.networking.k8s.io/v1
kind: Gateway
metadata:
  name: scavenger-hunt-gateway
  namespace: scavenger-hunt-staging
spec:
  addresses:
  - type: Hostname
    value: staging.scavengerhunt.example.com
---
# Update HTTPRoutes with staging hostnames
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api-route
  namespace: scavenger-hunt-staging
spec:
  hostnames:
  - staging.scavengerhunt.example.com
  - api-staging.scavengerhunt.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin-dashboard-route
  namespace: scavenger-hunt-staging
spec:
  hostnames:
  - staging.scavengerhunt.example.com
  - admin-staging.scavengerhunt.example.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: player-app-route
  namespace: scavenger-hunt-staging
spec:
  hostnames:
  - staging.scavengerhunt.example.com
  - play-staging.scavengerhunt.example.com
---
# Staging Certificate (using Let's Encrypt staging)
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scavenger-hunt-tls
  namespace: scavenger-hunt-staging
spec:
  dnsNames:
  - staging.scavengerhunt.example.com
  - "*.staging.scavengerhunt.example.com"
  issuerRef:
    name: letsencrypt-staging
    kind: ClusterIssuer
---
# Relaxed rate limits for staging/testing
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: api-ratelimit-policy
  namespace: scavenger-hunt-staging
spec:
  rateLimit:
    requests: 200  # Increased for testing
    burst: 50
---
# Higher sampling rate for staging
apiVersion: gateway.nginx.org/v1alpha1
kind: ObservabilityPolicy
metadata:
  name: tracing-policy
  namespace: scavenger-hunt-staging
spec:
  tracing:
    otel:
      samplingRate: 0.5  # 50% sampling in staging for better debugging