apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt-staging

resources:
  - ../../base
  - ../../base/gateway-api
  - ../../base/policies
  - certificate.yaml

namePrefix: staging-

commonLabels:
  environment: staging

replicas:
  - name: backend
    count: 1
  - name: player
    count: 1
  - name: admin
    count: 1

patchesStrategicMerge:
  - gateway-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=staging
      - LOG_LEVEL=warn