# NGINX Gateway Fabric Custom Resource Definitions
# These CRDs must be installed before the policies can be used
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: clientsettingspolicies.gateway.nginx.org
spec:
  group: gateway.nginx.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetRef:
                type: object
                properties:
                  group:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
              body:
                type: object
                properties:
                  maxSize:
                    type: string
                  timeout:
                    type: string
              headers:
                type: object
                properties:
                  maxSize:
                    type: string
                  add:
                    type: array
                    items:
                      type: object
                      properties:
                        name:
                          type: string
                        value:
                          type: string
              rateLimit:
                type: object
                properties:
                  requests:
                    type: integer
                  burst:
                    type: integer
                  key:
                    type: string
                  zoneSize:
                    type: string
                  dryRun:
                    type: boolean
                  logLevel:
                    type: string
                  rejectCode:
                    type: integer
              connectionLimit:
                type: object
                properties:
                  connections:
                    type: integer
                  dryRun:
                    type: boolean
              timeouts:
                type: object
                properties:
                  request:
                    type: string
                  keepalive:
                    type: string
                  proxyConnect:
                    type: string
                  proxyRead:
                    type: string
                  proxySend:
                    type: string
              retries:
                type: object
                properties:
                  attempts:
                    type: integer
                  conditions:
                    type: array
                    items:
                      type: string
                  perTryTimeout:
                    type: string
              circuitBreaker:
                type: object
                properties:
                  consecutiveErrors:
                    type: integer
                  interval:
                    type: string
                  baseEjectionTime:
                    type: string
                  maxEjectionPercent:
                    type: integer
  scope: Namespaced
  names:
    plural: clientsettingspolicies
    singular: clientsettingspolicy
    kind: ClientSettingsPolicy
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: observabilitypolicies.gateway.nginx.org
spec:
  group: gateway.nginx.org
  versions:
  - name: v1alpha1
    served: true
    storage: true
    schema:
      openAPIV3Schema:
        type: object
        properties:
          spec:
            type: object
            properties:
              targetRef:
                type: object
                properties:
                  group:
                    type: string
                  kind:
                    type: string
                  name:
                    type: string
              accessLog:
                type: object
                properties:
                  enabled:
                    type: boolean
                  format:
                    type: string
                  fields:
                    type: array
                    items:
                      type: string
                  filters:
                    type: array
                    items:
                      type: object
                      properties:
                        condition:
                          type: string
              metrics:
                type: object
                properties:
                  enabled:
                    type: boolean
                  port:
                    type: integer
                  secure:
                    type: boolean
                  path:
                    type: string
                  collectors:
                    type: array
                    items:
                      type: string
              tracing:
                type: object
                properties:
                  enabled:
                    type: boolean
                  otel:
                    type: object
                    properties:
                      endpoint:
                        type: string
                      serviceName:
                        type: string
                      samplingRate:
                        type: number
                      propagation:
                        type: array
                        items:
                          type: string
              healthCheck:
                type: object
                properties:
                  upstream:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      interval:
                        type: string
                      jitter:
                        type: string
                      fails:
                        type: integer
                      passes:
                        type: integer
                      timeout:
                        type: string
                  status:
                    type: object
                    properties:
                      enabled:
                        type: boolean
                      path:
                        type: string
                      detailed:
                        type: boolean
              errorPages:
                type: array
                items:
                  type: object
                  properties:
                    codes:
                      type: array
                      items:
                        type: integer
                    return:
                      type: object
                      properties:
                        code:
                          type: integer
                        body:
                          type: string
                        headers:
                          type: array
                          items:
                            type: object
                            properties:
                              name:
                                type: string
                              value:
                                type: string
  scope: Namespaced
  names:
    plural: observabilitypolicies
    singular: observabilitypolicy
    kind: ObservabilityPolicy