apiVersion: skaffold/v4beta8
kind: Config
metadata:
  name: scavenger-hunt

build:
  artifacts:
    - image: scavenger-hunt-backend
      context: backend
      docker:
        dockerfile: Dockerfile

    - image: scavenger-hunt-player
      context: frontend/player
      docker:
        dockerfile: Dockerfile

    - image: scavenger-hunt-admin
      context: frontend/admin
      docker:
        dockerfile: Dockerfile

  local:
    push: false
    useBuildkit: true

deploy:
  kubectl: {}

manifests:
  kustomize:
    paths:
      - kustomize/overlays/development

portForward:
  - resourceType: service
    resourceName: dev-backend
    namespace: scavenger-hunt-dev
    port: 80
    localPort: 3000

  - resourceType: service
    resourceName: dev-player
    namespace: scavenger-hunt-dev
    port: 80
    localPort: 3001

  - resourceType: service
    resourceName: dev-admin
    namespace: scavenger-hunt-dev
    port: 80
    localPort: 3002

profiles:
  - name: dev
    build:
      artifacts:
        - image: scavenger-hunt-backend
          context: backend
          docker:
            dockerfile: Dockerfile.dev
          sync:
            manual:
              - src: 'src/**/*.ts'
                dest: /app/src
              - src: 'src/**/*.js'
                dest: /app/src
              - src: 'package.json'
                dest: /app
              - src: 'tsconfig.json'
                dest: /app

        - image: scavenger-hunt-player
          context: frontend/player
          docker:
            dockerfile: Dockerfile.dev
          sync:
            manual:
              - src: 'app/**/*'
                dest: /app/app
              - src: 'components/**/*'
                dest: /app/components
              - src: 'utils/**/*'
                dest: /app/utils
              - src: 'public/**/*'
                dest: /app/public
              - src: 'package.json'
                dest: /app
              - src: 'next.config.js'
                dest: /app
              - src: 'tsconfig.json'
                dest: /app

        - image: scavenger-hunt-admin
          context: frontend/admin
          docker:
            dockerfile: Dockerfile.dev
          sync:
            manual:
              - src: 'app/**/*'
                dest: /app/app
              - src: 'components/**/*'
                dest: /app/components
              - src: 'utils/**/*'
                dest: /app/utils
              - src: 'public/**/*'
                dest: /app/public
              - src: 'package.json'
                dest: /app
              - src: 'next.config.js'
                dest: /app
              - src: 'tsconfig.json'
                dest: /app

  - name: production
    build:
      tagPolicy:
        gitCommit: {}
    manifests:
      kustomize:
        paths:
          - kustomize/overlays/production