# Cert-Manager Namespace
# Note: cert-manager itself should be installed cluster-wide using:
# kubectl apply -f https://github.com/cert-manager/cert-manager/releases/download/v1.15.0/cert-manager.yaml
---
apiVersion: v1
kind: Namespace
metadata:
  name: cert-manager