apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt-dev

bases:
  - ../../base

namePrefix: dev-

commonLabels:
  environment: development

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug