apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt-dev

resources:
  - ../../base
  - ../../base/gateway-api
  - ../../base/policies

namePrefix: dev-

labels:
  - pairs:
      environment: development

patches:
  - path: deployment-patch.yaml
  - path: gateway-patch.yaml
  - path: storage-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=development
      - LOG_LEVEL=debug

# Use local images for development
images:
  - name: ghcr.io/douglaslinsmeyer/scavenger-hunt-backend
    newName: scavenger-hunt-backend
    newTag: local
  - name: ghcr.io/douglaslinsmeyer/scavenger-hunt-player
    newName: scavenger-hunt-player  
    newTag: local
  - name: ghcr.io/douglaslinsmeyer/scavenger-hunt-admin
    newName: scavenger-hunt-admin
    newTag: local