# Additional permissions for NGINX Gateway controller
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: nginx-gateway-additional
rules:
# Missing namespace permissions
- apiGroups:
  - ""
  resources:
  - namespaces
  verbs:
  - get
  - list
  - watch
# Missing CRD permissions
- apiGroups:
  - apiextensions.k8s.io
  resources:
  - customresourcedefinitions
  verbs:
  - get
  - list
  - watch
# Missing NGINX Gateway CRD permissions
- apiGroups:
  - gateway.nginx.org
  resources:
  - nginxproxies
  - upstreamsettingspolicies
  verbs:
  - get
  - list
  - watch
# Leader election permissions
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
---
# Bind additional permissions to the service account
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: nginx-gateway-additional
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: nginx-gateway-additional
subjects:
- kind: ServiceAccount
  name: nginx-gateway
  namespace: nginx-gateway