# Production Certificate
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scavenger-hunt-tls
spec:
  secretName: scavenger-hunt-tls
  dnsNames:
  - scavenger-hunt.linsmeyer.com
  issuerRef:
    name: letsencrypt-prod-gateway
    kind: ClusterIssuer