# Production-specific patches for NGINX Fabric Gateway
---
# Update HTTPRoutes with production hostnames and proper routing
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api-route
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  - api.scavenger-hunt.linsmeyer.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: X-Forwarded-Prefix
          value: /api
  - matches:
    - path:
        type: PathPrefix
        value: /socket.io
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin-dashboard-route
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  - admin.scavenger-hunt.linsmeyer.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /admin
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: X-Forwarded-Prefix
          value: /admin
  - matches:
    - path:
        type: PathPrefix
        value: /admin/_next
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: player-app-route
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  - play.scavenger-hunt.linsmeyer.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  - "*.scavenger-hunt.linsmeyer.com"
---
# Stricter rate limits for production
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: api-ratelimit-policy
spec:
  rateLimit:
    requests: 60  # Reduced from 100 for production
    burst: 10     # Reduced from 20
# Production observability settings
# NOTE: ObservabilityPolicy v1alpha2 CRDs not available in production cluster
# Tracing is disabled until CRDs are installed
