# Production-specific patches for NGINX Fabric Gateway
---
# Update HTTPRoutes with production hostnames and proper routing
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: backend-api-route
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /api
    backendRefs:
    - name: backend
      port: 80
    filters:
    - type: RequestHeaderModifier
      requestHeaderModifier:
        add:
        - name: X-Forwarded-Prefix
          value: /api
  - matches:
    - path:
        type: PathPrefix
        value: /socket.io
    backendRefs:
    - name: backend
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: admin-dashboard-route
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  rules:
  - matches:
    - path:
        type: PathPrefix
        value: /admin
    backendRefs:
    - name: admin
      port: 80
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: player-app-route
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
---
apiVersion: gateway.networking.k8s.io/v1
kind: HTTPRoute
metadata:
  name: https-redirect
spec:
  hostnames:
  - scavenger-hunt.linsmeyer.com
  rules:
  # Exclude ACME challenges from HTTPS redirect
  - matches:
    - path:
        type: PathPrefix
        value: /.well-known/acme-challenge/
    # No filters - let it pass through to other routes
  # Redirect everything else to HTTPS
  - matches:
    - path:
        type: PathPrefix
        value: /
    filters:
    - type: RequestRedirect
      requestRedirect:
        scheme: https
        statusCode: 301
---
# Production observability settings
# NOTE: ObservabilityPolicy v1alpha2 CRDs not available in production cluster
# Tracing is disabled until CRDs are installed
# NOTE: ClientSettingsPolicy in NGINX Gateway Fabric v2.0.2 only supports body, keepAlive, and targetRef fields
# Rate limiting, headers, timeouts, and retries must be configured differently
