apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt-prod

resources:
  - ../../base
  - ../../base/gateway-api
  - ../../base/policies
  - certificate.yaml
  - security-headers-policy.yaml

commonLabels:
  environment: production

replicas:
  - name: backend
    count: 1
  - name: player
    count: 1
  - name: admin
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml
  - gateway-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info