apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt-prod

resources:
  - ../../base
  - ../../base/gateway-api
  - ../../base/policies
  - certificate-subdomains.yaml

# Labels removed to avoid selector immutability issues
# Production environment label will be added via deployment patches if needed

replicas:
  - name: backend
    count: 1
  - name: player
    count: 1
  - name: admin
    count: 1

patches:
  - path: deployment-patch.yaml
  - path: gateway-patch.yaml
  - path: storage-patch.yaml
  - path: gateway-cert-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info