apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt-prod

bases:
  - ../../base

commonLabels:
  environment: production

replicas:
  - name: backend
    count: 2
  - name: player
    count: 2
  - name: admin
    count: 1

patchesStrategicMerge:
  - deployment-patch.yaml

configMapGenerator:
  - name: app-config
    literals:
      - NODE_ENV=production
      - LOG_LEVEL=info