apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: ssdv2
  resources:
    requests:
      storage: 100Gi  # Minimum size required for ssdv2
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: ssdv2
  resources:
    requests:
      storage: 100Gi  # Minimum size required for ssdv2