apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
spec:
  storageClassName: sata
  resources:
    requests:
      storage: 10Gi  # Larger size for production
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
spec:
  storageClassName: sata
  resources:
    requests:
      storage: 5Gi  # Production size