apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt

resources:
  - namespace.yaml
  # PostgreSQL database
  - postgres-pvc.yaml
  - postgres-deployment.yaml
  - postgres-service.yaml
  # Redis cache
  - redis-pvc.yaml
  - redis-deployment.yaml
  - redis-service.yaml
  # Application services
  - backend-deployment.yaml
  - backend-service.yaml
  - player-deployment.yaml
  - player-service.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  # Comment out old ingress when using NGINX Fabric Gateway
  # - ingress.yaml
  
  # NGINX Fabric Gateway resources
  # - nginx-fabric/  # Should be deployed separately to nginx-gateway namespace
  # - gateway-api/    # Production-specific, moved to production overlay
  # - policies/       # Production-specific, moved to production overlay

labels:
  - pairs:
      app.kubernetes.io/name: scavenger-hunt
      app.kubernetes.io/part-of: scavenger-hunt

images:
  - name: scavenger-hunt-backend
    newName: ghcr.io/douglaslinsmeyer/scavenger-hunt-backend
    newTag: latest
  - name: scavenger-hunt-player
    newName: ghcr.io/douglaslinsmeyer/scavenger-hunt-player
    newTag: latest
  - name: scavenger-hunt-admin
    newName: ghcr.io/douglaslinsmeyer/scavenger-hunt-admin
    newTag: latest