apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: scavenger-hunt

resources:
  - namespace.yaml
  - backend-deployment.yaml
  - backend-service.yaml
  - player-deployment.yaml
  - player-service.yaml
  - admin-deployment.yaml
  - admin-service.yaml
  # Comment out old ingress when using NGINX Fabric Gateway
  # - ingress.yaml
  
  # NGINX Fabric Gateway resources
  - nginx-fabric/
  - gateway-api/
  - policies/

commonLabels:
  app.kubernetes.io/name: scavenger-hunt
  app.kubernetes.io/part-of: scavenger-hunt

images:
  - name: scavenger-hunt-backend
    newName: ghcr.io/douglaslinsmeyer/scavenger-hunt-backend
    newTag: latest
  - name: scavenger-hunt-player
    newName: ghcr.io/douglaslinsmeyer/scavenger-hunt-player
    newTag: latest
  - name: scavenger-hunt-admin
    newName: ghcr.io/douglaslinsmeyer/scavenger-hunt-admin
    newTag: latest