apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-pvc
  labels:
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Rackspace minimum PVC size
  # Use sata for cost-effective storage in production
  # For local development, we'll override this with the default storage class
  storageClassName: sata