apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: redis-pvc
  labels:
    app.kubernetes.io/component: cache
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 5Gi  # Rackspace minimum PVC size
  # Use sata for cost-effective storage
  # Redis is mostly in-memory, disk is for persistence
  storageClassName: sata