# TLS Certificate configuration using cert-manager
# This will automatically provision and renew SSL certificates
---
# Certificate for production domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scavenger-hunt-tls
  namespace: scavenger-hunt-prod
spec:
  secretName: scavenger-hunt-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - scavenger-hunt.linsmeyer.com
  - "*.scavenger-hunt.linsmeyer.com"
  - api.scavenger-hunt.linsmeyer.com
  - admin.scavenger-hunt.linsmeyer.com
  - play.scavenger-hunt.linsmeyer.com
  # Certificate renewal
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days before expiry
---
# ClusterIssuer for Let's Encrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: doug@linsmeyer.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
# ClusterIssuer for Let's Encrypt Staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: doug@linsmeyer.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          class: nginx
---
# Self-signed certificate for development
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scavenger-hunt-tls-dev
  namespace: scavenger-hunt-dev
spec:
  secretName: scavenger-hunt-tls
  issuerRef:
    name: selfsigned-issuer
    kind: ClusterIssuer
  dnsNames:
  - localhost
  - scavenger-hunt.local
  - "*.scavenger-hunt.local"
  duration: 8760h # 1 year
---
# Self-signed ClusterIssuer for development
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: selfsigned-issuer
spec:
  selfSigned: {}
---
# TLS Policy for Gateway
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: tls-policy
  namespace: scavenger-hunt-prod
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: scavenger-hunt-gateway
  tls:
    # Minimum TLS version
    minimumVersion: "1.2"
    # Preferred TLS version
    preferredVersion: "1.3"
    # Cipher suites (strong security)
    ciphers:
    - TLS_AES_128_GCM_SHA256
    - TLS_AES_256_GCM_SHA384
    - TLS_CHACHA20_POLY1305_SHA256
    - ECDHE-RSA-AES128-GCM-SHA256
    - ECDHE-RSA-AES256-GCM-SHA384
    # HSTS configuration
    hsts:
      enabled: true
      maxAge: 31536000
      includeSubdomains: true
      preload: true