# TLS Certificate configuration using cert-manager
# This will automatically provision and renew SSL certificates
---
# Certificate for production domain
apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: scavenger-hunt-tls
  namespace: scavenger-hunt-prod
spec:
  secretName: scavenger-hunt-tls
  issuerRef:
    name: letsencrypt-prod
    kind: ClusterIssuer
  dnsNames:
  - scavenger-hunt.linsmeyer.com
  - "*.scavenger-hunt.linsmeyer.com"
  - api.scavenger-hunt.linsmeyer.com
  - admin.scavenger-hunt.linsmeyer.com
  - play.scavenger-hunt.linsmeyer.com
  # Certificate renewal
  duration: 2160h # 90 days
  renewBefore: 720h # 30 days before expiry
---
# ClusterIssuer for Let's Encrypt Production
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-prod
spec:
  acme:
    server: https://acme-v02.api.letsencrypt.org/directory
    email: doug@linsmeyer.com
    privateKeySecretRef:
      name: letsencrypt-prod-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
---
# ClusterIssuer for Let's Encrypt Staging (for testing)
apiVersion: cert-manager.io/v1
kind: ClusterIssuer
metadata:
  name: letsencrypt-staging
spec:
  acme:
    server: https://acme-staging-v02.api.letsencrypt.org/directory
    email: doug@linsmeyer.com
    privateKeySecretRef:
      name: letsencrypt-staging-account-key
    solvers:
    - http01:
        ingress:
          ingressClassName: nginx
