# Client Body Size Policy for NGINX Gateway Fabric
# Configures maximum request body sizes for different routes
# NOTE: NGINX Gateway Fabric v2.0.2 only supports body, keepAlive, and targetRef fields
---
# API Body Size Policy - Large for photo uploads
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: api-bodysize-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend-api-route
  body:
    # 50MB limit for photo uploads
    maxSize: 50m
---
# Admin Dashboard Body Size Policy - Moderate size
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: admin-bodysize-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: admin-dashboard-route
  body:
    # 10MB limit for admin operations
    maxSize: 10m
---
# Player App Body Size Policy - Standard size
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: player-bodysize-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: player-app-route
  body:
    # 5MB limit for player interactions
    maxSize: 5m