# Timeout and Retry Policies for NGINX Gateway Fabric
# Configures appropriate timeouts for different service types
---
# Backend API Timeout Policy
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: api-timeout-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend-api-route
  timeouts:
    # Standard API request timeout
    request: 30s
    # Keep connection alive for efficiency
    keepalive: 65s
    # Proxy timeouts
    proxyConnect: 10s
    proxySend: 30s
    proxyRead: 30s
  retries:
    # Retry failed requests up to 3 times
    attempts: 3
    perTryTimeout: 10s
    conditions:
    - 5xx
    - reset
    - refused
    - timeout
---
# WebSocket Timeout Policy - Extended for real-time connections
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: websocket-timeout-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: backend-api-route
  timeouts:
    # Long timeout for WebSocket connections
    request: 3600s
    keepalive: 3600s
    proxyConnect: 10s
    proxySend: 3600s
    proxyRead: 3600s
  # No retries for WebSocket connections
  retries:
    attempts: 0
---
# Frontend Apps Timeout Policy
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: frontend-timeout-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: admin-dashboard-route
  timeouts:
    # Shorter timeout for static content
    request: 15s
    keepalive: 65s
    proxyConnect: 5s
    proxySend: 15s
    proxyRead: 15s
  retries:
    attempts: 2
    perTryTimeout: 5s
    conditions:
    - 5xx
    - refused
    - timeout
---
# Player App Timeout Policy - Same as admin
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: player-timeout-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: HTTPRoute
    name: player-app-route
  timeouts:
    request: 15s
    keepalive: 65s
    proxyConnect: 5s
    proxySend: 15s
    proxyRead: 15s
  retries:
    attempts: 2
    perTryTimeout: 5s
    conditions:
    - 5xx
    - refused
    - timeout
---
# Circuit Breaker Policy - Prevent cascading failures
apiVersion: gateway.nginx.org/v1alpha1
kind: ClientSettingsPolicy
metadata:
  name: circuit-breaker-policy
spec:
  targetRef:
    group: gateway.networking.k8s.io
    kind: Gateway
    name: scavenger-hunt-gateway
  circuitBreaker:
    # Trip circuit after 5 consecutive failures
    consecutiveErrors: 5
    # Check every 10 seconds
    interval: 10s
    # Recovery timeout
    baseEjectionTime: 30s
    # Maximum percentage of upstream servers that can be ejected
    maxEjectionPercent: 50