name: Check Deployment Status

on:
  workflow_dispatch:

env:
  NAMESPACE: scavenger-hunt-prod

jobs:
  check-status:
    name: Check Deployment Status
    runs-on: ubuntu-latest
    
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup kubectl
        uses: azure/setup-kubectl@v3
        with:
          version: 'latest'

      - name: Configure kubectl
        run: |
          mkdir -p $HOME/.kube
          # Check if the secret is already base64 encoded or not
          if echo "${{ secrets.KUBE_CONFIG }}" | base64 -d >/dev/null 2>&1; then
            echo "Kubeconfig is base64 encoded, decoding..."
            echo "${{ secrets.KUBE_CONFIG }}" | base64 -d > $HOME/.kube/config
          else
            echo "Kubeconfig is plain text, using directly..."
            echo "${{ secrets.KUBE_CONFIG }}" > $HOME/.kube/config
          fi
          chmod 600 $HOME/.kube/config

      - name: Check namespace and resources
        run: |
          echo "=== Checking namespace ==="
          kubectl get namespace ${{ env.NAMESPACE }} -o yaml || echo "Namespace not found"
          
          echo -e "\n=== Checking deployments ==="
          kubectl get deployments -n ${{ env.NAMESPACE }} -o wide || echo "No deployments found"
          
          echo -e "\n=== Checking pods ==="
          kubectl get pods -n ${{ env.NAMESPACE }} -o wide || echo "No pods found"
          
          echo -e "\n=== Checking services ==="
          kubectl get services -n ${{ env.NAMESPACE }} || echo "No services found"
          
          echo -e "\n=== Checking events ==="
          kubectl get events -n ${{ env.NAMESPACE }} --sort-by='.lastTimestamp' | tail -20 || echo "No events found"

      - name: Check pod details
        run: |
          echo "=== Checking pod details ==="
          for pod in $(kubectl get pods -n ${{ env.NAMESPACE }} -o name 2>/dev/null | cut -d/ -f2); do
            echo -e "\n--- Pod: $pod ---"
            kubectl describe pod $pod -n ${{ env.NAMESPACE }}
            echo -e "\n--- Pod logs: $pod ---"
            kubectl logs $pod -n ${{ env.NAMESPACE }} --tail=50 || true
          done

      - name: Check image pull secrets
        run: |
          echo "=== Checking image pull secrets ==="
          kubectl get secrets -n ${{ env.NAMESPACE }} || echo "No secrets found"
          
          echo -e "\n=== Checking service accounts ==="
          kubectl get serviceaccounts -n ${{ env.NAMESPACE }} -o yaml || echo "No service accounts found"